name: Build PR (Manual)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR Number to build"
        required: true
        type: number

jobs:
  now:
    runs-on: windows-2022

    steps:
      - name: Get PR Info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ inputs.pr_number }}
            });
            return {
              ref: pr.data.head.ref,
              sha: pr.data.head.sha,
              repo: pr.data.head.repo.full_name
            };

      - uses: actions/checkout@v4
        with:
          repository: ${{ fromJSON(steps.pr.outputs.result).repo }}
          ref: ${{ fromJSON(steps.pr.outputs.result).sha }}

      - name: Build
        shell: pwsh
        run: |
          python build.py
          copy src/rndx_compiled.lua C:\rndx.lua

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rndx-pr-${{ inputs.pr_number }}
          path: C:\rndx.lua
          retention-days: 30
